// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// whichdiffincyl
List whichdiffincyl(NumericMatrix mat, NumericVector dir, NumericVector r_sq, NumericVector t);
RcppExport SEXP _genfun_whichdiffincyl(SEXP matSEXP, SEXP dirSEXP, SEXP r_sqSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dir(dirSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r_sq(r_sqSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(whichdiffincyl(mat, dir, r_sq, t));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genfun_whichdiffincyl", (DL_FUNC) &_genfun_whichdiffincyl, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_genfun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
