# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Is the difference of two points contained in a cylinder?
#'
#' The function finds out if the vector between two point \code{x_1} and \code{x_2}
#' is contained in a specified cylinder.
#' Moreover, is \code{x_2} contained in some cylinder extending from \code{x_1}.
#' @param mat A matrix in which the rows represent a point in some three dimensional space.
#' @param dir A vector of the same dimension as the points.
#' @param r_sq A vector or single value of squared radii of a cylinder.
#' @param t A vector or single value of heights of a cylinder.
#' @return A \code{\link{list}} of \code{\link{data.frame}s}
#' where each list element is a unique combination of radius and height of the cylinder.
#' Each \code{\link{data.frame}} have two columns: \code{index1} and \code{index2}, s.t.
#' \code{mat[index2, ] - mat[index1, ]} is contained in the specified cylinder.
#' @details This function also works for two dimensions. In which case \code{r_sq} is half the width squared
#' @useDynLib genfun
#' @importFrom Rcpp sourceCpp
#' @export
whichdiffincyl <- function(mat, dir, r_sq, t) {
    .Call('_genfun_whichdiffincyl', PACKAGE = 'genfun', mat, dir, r_sq, t)
}

